/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Addemployeeform.java
 *
 * Created on 31 May, 2014, 12:37:56 PM
 */

package employeeproject;
import javax.swing.*;
import java.sql.*;
import java.text.*;
import java.util.Date;
import java.awt.event.*;
//import java.text.DateFormat;

/**
 *
 * @author hpworld
 */
public class Addemployeeform extends javax.swing.JFrame {

    /** Creates new form Addemployeeform */
    public Addemployeeform() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txteno = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcontactno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtdoj = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txttiming = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtsalary = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        txtemailid = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox();
        dcombo = new javax.swing.JComboBox();
        pcombo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(670, 402));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("ADD NEW EMPLOYEE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 30, 310, 35);

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Employee ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 100, 130, 22);

        jLabel3.setBackground(new java.awt.Color(255, 153, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(430, 100, 80, 22);

        txteno.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txteno.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(txteno);
        txteno.setBounds(230, 100, 90, 30);

        txtname.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtname.setForeground(new java.awt.Color(0, 0, 153));
        txtname.setPreferredSize(new java.awt.Dimension(8, 20));
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnameKeyTyped(evt);
            }
        });
        jPanel1.add(txtname);
        txtname.setBounds(540, 100, 170, 30);

        jLabel4.setBackground(new java.awt.Color(255, 153, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Father's name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 140, 140, 22);

        txtfname.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtfname.setForeground(new java.awt.Color(0, 0, 153));
        txtfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfnameKeyTyped(evt);
            }
        });
        jPanel1.add(txtfname);
        txtfname.setBounds(230, 140, 160, 30);

        jLabel5.setBackground(new java.awt.Color(255, 153, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Age");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(430, 140, 70, 22);

        txtage.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtage.setForeground(new java.awt.Color(0, 0, 153));
        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtageKeyPressed(evt);
            }
        });
        jPanel1.add(txtage);
        txtage.setBounds(540, 140, 170, 30);

        jLabel6.setBackground(new java.awt.Color(255, 153, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Gender");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 180, 90, 22);

        jLabel7.setBackground(new java.awt.Color(255, 153, 0));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("Contact No.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(430, 180, 120, 22);

        txtcontactno.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtcontactno.setForeground(new java.awt.Color(0, 0, 153));
        txtcontactno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcontactnoKeyPressed(evt);
            }
        });
        jPanel1.add(txtcontactno);
        txtcontactno.setBounds(540, 180, 170, 30);

        jLabel8.setBackground(new java.awt.Color(255, 153, 0));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Department");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 220, 120, 22);

        jLabel9.setBackground(new java.awt.Color(255, 153, 0));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("Post");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(430, 220, 70, 22);

        txtdoj.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtdoj.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(txtdoj);
        txtdoj.setBounds(230, 260, 160, 30);

        jLabel10.setBackground(new java.awt.Color(255, 153, 0));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("Date of joining");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(100, 260, 130, 22);

        jLabel11.setBackground(new java.awt.Color(255, 153, 0));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 102));
        jLabel11.setText("Timing");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(430, 260, 100, 22);

        txttiming.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txttiming.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(txttiming);
        txttiming.setBounds(540, 260, 170, 30);

        jLabel12.setBackground(new java.awt.Color(255, 153, 0));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 102));
        jLabel12.setText("Salary");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(100, 300, 90, 22);

        txtsalary.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtsalary.setForeground(new java.awt.Color(0, 0, 153));
        txtsalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsalaryKeyPressed(evt);
            }
        });
        jPanel1.add(txtsalary);
        txtsalary.setBounds(230, 300, 160, 30);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        save.setBackground(new java.awt.Color(255, 255, 255));
        save.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save);
        save.setBounds(20, 10, 90, 30);

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel2.add(exit);
        exit.setBounds(120, 10, 100, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(290, 380, 237, 58);

        txtemailid.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtemailid.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(txtemailid);
        txtemailid.setBounds(540, 300, 170, 30);

        jLabel13.setBackground(new java.awt.Color(255, 153, 0));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 102));
        jLabel13.setText("Email ID");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(430, 300, 100, 22);

        txtaddress.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtaddress.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.add(txtaddress);
        txtaddress.setBounds(230, 340, 480, 30);

        jLabel14.setBackground(new java.awt.Color(255, 153, 0));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 102));
        jLabel14.setText("Address");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(100, 340, 100, 22);

        combo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel1.add(combo);
        combo.setBounds(230, 180, 160, 30);

        dcombo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        jPanel1.add(dcombo);
        dcombo.setBounds(230, 220, 160, 30);

        pcombo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Manager", "Teaam leader", "Project manager", "Sales Manager", "HR" }));
        jPanel1.add(pcombo);
        pcombo.setBounds(540, 220, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if(txtage.getText().equals("")||txtname.getText().equals("")||txtsalary.getText().equals("")||txtaddress.getText().equals("")||txtcontactno.getText().equals("")||txttiming.getText().equals("")||txtdoj.getText().equals("")||txtemailid.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please fill all fields");
            return;
        }
        int eno,age;
        long salary;
        String name,gender,dept,post,address,cno,time,doj,fname,eid;
        eno=Integer.parseInt(txteno.getText());
        age=Integer.parseInt(txtage.getText());
        salary=Long.parseLong(txtsalary.getText());
        name=txtname.getText();
        address=txtaddress.getText();
        gender=combo.getSelectedItem().toString();
        dept=dcombo.getSelectedItem().toString();
        post=pcombo.getSelectedItem().toString();
        cno=txtcontactno.getText();
        time=txttiming.getText();
        doj=txtdoj.getText();
        fname=txtfname.getText();
        eid=txtemailid.getText();
        String mode="np";
        if(cno.length()!=10)
        {
            JOptionPane.showMessageDialog(null, "Invalid Contact No.");
            return;
        }
       
        try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:employee");
            Statement stmt=con.createStatement();
            String query;
            query="insert into etable values("+eno+",'"+name+"','"+fname+"',"+age+",'"+gender+"','"+cno+"','"+dept+"','"+post+"','"+doj+"','"+time+"',"+salary+",'"+eid+"','"+address+"','"+mode+"')";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "successfully saved");
            txtname.setText("");
            txtfname.setText("");
            txtsalary.setText("");
            txtage.setText("");
            txtcontactno.setText("");
            dcombo.removeAllItems();
            txttiming.setText("");
            txtdoj.setText("");
            //txtpost.setText("");
            txtemailid.setText("");
            txtaddress.setText("");


       }
        catch(Exception e)
        {JOptionPane.showMessageDialog(rootPane, e.getMessage());}
    }//GEN-LAST:event_saveActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.hide();
    }//GEN-LAST:event_exitActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      int eno=0;
       try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:employee");
            Statement stmt=con.createStatement();
            ResultSet res=stmt.executeQuery("select * from etable");
            while(res.next())
            {

                 eno=Integer.parseInt(res.getString("eno"));
               
                
            }
          // eno++;
            txteno.setText(""+(eno+1));
            txteno.setEnabled(false);
            txtname.requestFocus();
            DateFormat df= new SimpleDateFormat("dd-MMM-yyyy");
            Date dt=new Date();
            txtdoj.setText(String.valueOf((df.format(dt))));
            txtdoj.setEnabled(false);
            
            //Add all department  in combo box
            
             ResultSet res2=stmt.executeQuery("select * from depttable");
             while(res2.next())
             {
                 dcombo.addItem(res2.getString(2));
             }
       }
       catch(Exception e)
       {}
    }//GEN-LAST:event_formWindowActivated

    private void txtnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyTyped
       char ch;
       ch=evt.getKeyChar();
       if(ch==KeyEvent.VK_ENTER)
       {
           txtfname.requestFocus();
       evt.consume();
       }
    }//GEN-LAST:event_txtnameKeyTyped

    private void txtfnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfnameKeyTyped
        char ch;
        ch=evt.getKeyChar();
        if(ch==KeyEvent.VK_ENTER) {
            txtage.requestFocus();
            evt.consume();
        }
}//GEN-LAST:event_txtfnameKeyTyped

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        // TODO add your handling code here:
        char ch;
        ch=evt.getKeyChar();
        if(!(ch==KeyEvent.VK_ENTER||ch==KeyEvent.VK_SPACE||ch==KeyEvent.VK_BACK_SPACE||ch>='A'&&ch<='Z'||ch>='a'&&ch<='z')) 
        {
            JOptionPane.showMessageDialog(null, "INVALID CHARACTER");
            txtage.requestFocus();
            evt.consume();
        }
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtfnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfnameKeyPressed
        char ch;
        ch=evt.getKeyChar();
        if(!(ch==KeyEvent.VK_ENTER||ch==KeyEvent.VK_SPACE||ch==KeyEvent.VK_BACK_SPACE||ch>='A'&&ch<='Z'||ch>='a'&&ch<='z')) 
        {
            JOptionPane.showMessageDialog(null, "Invalid Character");
            txtage.requestFocus();
            evt.consume();
        }
    }//GEN-LAST:event_txtfnameKeyPressed

    private void txtageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyPressed
       char ch;
        ch=evt.getKeyChar();
         if(!(ch==KeyEvent.VK_ENTER||ch==KeyEvent.VK_SPACE||ch==KeyEvent.VK_BACK_SPACE||ch>='0'&&ch<='9')) 

        {
            JOptionPane.showMessageDialog(null, "Invalid digit");
            txtage.requestFocus();
            evt.consume();
        }
    }//GEN-LAST:event_txtageKeyPressed

    private void txtcontactnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontactnoKeyPressed
        // TODO add your handling code here:
        char ch;
        ch=evt.getKeyChar();
                if(!(ch==KeyEvent.VK_ENTER||ch==KeyEvent.VK_SPACE||ch==KeyEvent.VK_BACK_SPACE||ch>='0'&&ch<='9')) 

        {
            JOptionPane.showMessageDialog(null, "Invalid digit");
            txtage.requestFocus();
            evt.consume();
        }
    }//GEN-LAST:event_txtcontactnoKeyPressed

    private void txtsalaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsalaryKeyPressed
       char ch;
        ch=evt.getKeyChar();
                 if(!(ch==KeyEvent.VK_ENTER||ch==KeyEvent.VK_SPACE||ch==KeyEvent.VK_BACK_SPACE||ch>='0'&&ch<='9')) 
 

        {
            JOptionPane.showMessageDialog(null, "Invalid digit");
            txtage.requestFocus();
            evt.consume();
        }
    }//GEN-LAST:event_txtsalaryKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addemployeeform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo;
    private javax.swing.JComboBox dcombo;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox pcombo;
    private javax.swing.JButton save;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcontactno;
    private javax.swing.JTextField txtdoj;
    private javax.swing.JTextField txtemailid;
    private javax.swing.JTextField txteno;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JTextField txttiming;
    // End of variables declaration//GEN-END:variables

}
