/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Deleteemployeeform.java
 *
 * Created on 1 Jun, 2014, 12:11:14 PM
 */

package employeeproject;
import java.sql.*;
import javax.swing.*;
import java.text.*;
import java.util.Date;

/**
 *
 * @author hpworld
 */
public class Deleteemployeeform extends javax.swing.JFrame {

    /** Creates new form Deleteemployeeform */
    public Deleteemployeeform() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txteno = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtsalary = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtdept = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdoj = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txttime = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtpost = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtemailid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("DELETE  EMPLOYEE RECORD");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 20, 440, 35);

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Employee ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(247, 90, 130, 22);

        jLabel3.setBackground(new java.awt.Color(255, 153, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(41, 172, 90, 22);

        txteno.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txteno.setForeground(new java.awt.Color(255, 102, 0));
        jPanel1.add(txteno);
        txteno.setBounds(387, 89, 160, 30);

        txtname.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtname.setForeground(new java.awt.Color(0, 0, 102));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtname);
        txtname.setBounds(180, 180, 160, 30);

        jLabel5.setBackground(new java.awt.Color(255, 153, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Age");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(382, 172, 80, 22);

        txtage.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtage.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(txtage);
        txtage.setBounds(489, 171, 160, 30);

        ok.setBackground(new java.awt.Color(255, 255, 255));
        ok.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok);
        ok.setBounds(310, 130, 100, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Salary");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 230, 90, 22);

        txtsalary.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtsalary.setForeground(new java.awt.Color(0, 0, 102));
        txtsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalaryActionPerformed(evt);
            }
        });
        jPanel1.add(txtsalary);
        txtsalary.setBounds(180, 230, 160, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Gnder");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 230, 90, 22);

        txtgender.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtgender.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(txtgender);
        txtgender.setBounds(490, 220, 160, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Contact No.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 280, 120, 22);

        txtcno.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtcno.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(txtcno);
        txtcno.setBounds(180, 280, 160, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Department");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(380, 270, 120, 22);

        txtdept.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtdept.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(txtdept);
        txtdept.setBounds(490, 270, 160, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Date of joining");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 330, 130, 22);

        txtdoj.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtdoj.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(txtdoj);
        txtdoj.setBounds(180, 330, 160, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Timing");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(380, 320, 90, 22);

        txttime.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txttime.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(txttime);
        txttime.setBounds(490, 320, 160, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Post");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 380, 80, 22);

        txtpost.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtpost.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(txtpost);
        txtpost.setBounds(180, 380, 160, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("Address");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(380, 370, 100, 22);

        txtaddress.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtaddress.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(txtaddress);
        txtaddress.setBounds(450, 370, 240, 30);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(250, 480, 237, 58);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("Fname");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 430, 90, 22);

        txtfname.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtfname.setForeground(new java.awt.Color(0, 0, 102));
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtfname);
        txtfname.setBounds(180, 430, 160, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("Email ID");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(380, 430, 100, 22);

        txtemailid.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtemailid.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(txtemailid);
        txtemailid.setBounds(490, 420, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
      int eno;
      eno=Integer.parseInt(txteno.getText());
        try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:employee");
            Statement stmt=con.createStatement();
            String query;
            query="select * from etable where eno="+eno+"";
            ResultSet res=stmt.executeQuery(query);
             DateFormat df= new SimpleDateFormat("dd-MMM-yyyy");

         
            if(res.next())
            {
                txtname.setText((res.getString("name")));
                txtsalary.setText((res.getString("salary")));
                txtdept.setText((res.getString("dept")));
                txtpost.setText((res.getString("post")));
                
                txttime.setText((res.getString("timing")));
                txtage.setText((res.getString("age")));
                txtcno.setText((res.getString("contactno")));
                txtaddress.setText((res.getString("address")));
                txtgender.setText((res.getString("gender")));
                txtdoj.setText(df.format(res.getDate("doj")));
                txtemailid.setText(res.getString("emailid"));
                txtfname.setText(res.getString("fname"));
            }
            else
                JOptionPane.showMessageDialog(null, "Not found");
                
            }
        catch(Exception e)
        {}
}//GEN-LAST:event_okActionPerformed

    private void txtsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalaryActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtsalaryActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int eno,age;
        eno=Integer.parseInt(txteno.getText());
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:employee");
            Statement stmt=con.createStatement();
            int choice;
            choice =JOptionPane.showConfirmDialog(null, "Are u sure...??");
            if(choice==JOptionPane.YES_OPTION)
            {

            String query;
            query="delete from etable where eno="+eno+"";
            stmt.executeUpdate(query);
            txteno.setText("");
            txtname.setText("");
            txtsalary.setText("");
            txtaddress.setText("");
            txtage.setText("");
            txtgender.setText("");
            txtcno.setText("");
            txtdept.setText("");
            txttime.setText("");
            txtdoj.setText("");
            txtpost.setText("");
            txtemailid.setText("");
            txtfname.setText("");
             JOptionPane.showMessageDialog(null, "successfully deleted");
            }


        } catch(Exception e) {
        }
}//GEN-LAST:event_deleteActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.hide();
}//GEN-LAST:event_exitActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtfnameActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deleteemployeeform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton ok;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcno;
    private javax.swing.JTextField txtdept;
    private javax.swing.JTextField txtdoj;
    private javax.swing.JTextField txtemailid;
    private javax.swing.JTextField txteno;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpost;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JTextField txttime;
    // End of variables declaration//GEN-END:variables

}
