/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DeletePaysalform.java
 *
 * Created on Jun 2, 2014, 7:01:09 AM
 */

package employeeproject;
import java.sql.*;
import javax.swing.*;
import java.text.*;

/**
 *
 * @author Neeraj
 */
public class Deletepaidsalaryform extends javax.swing.JFrame {

    /** Creates new form DeletePaysalform */
    public Deletepaidsalaryform() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtsno1 = new javax.swing.JTextField();
        txtsdate1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txteno1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtname1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtsalary1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtage1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtgender1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtcno1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtdept1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtpost1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtdoj1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txttime1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtaddress1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txthra = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txttotal1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        ok1 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        txtda = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtta = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtpf = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setForeground(new java.awt.Color(255, 153, 0));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("DELETE PAID SALARY RECORD");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(160, 20, 440, 50);

        jLabel18.setBackground(new java.awt.Color(102, 51, 0));
        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("Enter paid salary no.");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(199, 92, 162, 22);
        jPanel3.add(txtsno1);
        txtsno1.setBounds(386, 90, 130, 30);
        jPanel3.add(txtsdate1);
        txtsdate1.setBounds(540, 170, 170, 30);

        jLabel19.setBackground(new java.awt.Color(102, 51, 0));
        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 102));
        jLabel19.setText("Employee no.");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(43, 171, 140, 22);
        jPanel3.add(txteno1);
        txteno1.setBounds(153, 169, 170, 30);

        jLabel20.setBackground(new java.awt.Color(102, 51, 0));
        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setText("Name");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(43, 209, 90, 22);
        jPanel3.add(txtname1);
        txtname1.setBounds(153, 207, 170, 30);

        jLabel21.setBackground(new java.awt.Color(102, 51, 0));
        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 102));
        jLabel21.setText("Salary");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(400, 210, 90, 22);
        jPanel3.add(txtsalary1);
        txtsalary1.setBounds(540, 210, 170, 30);

        jLabel22.setBackground(new java.awt.Color(102, 51, 0));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 102));
        jLabel22.setText("Age");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(43, 247, 80, 22);
        jPanel3.add(txtage1);
        txtage1.setBounds(153, 245, 170, 30);

        jLabel23.setBackground(new java.awt.Color(102, 51, 0));
        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 102));
        jLabel23.setText("Gender");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(400, 250, 100, 22);
        jPanel3.add(txtgender1);
        txtgender1.setBounds(540, 250, 170, 30);

        jLabel24.setBackground(new java.awt.Color(102, 51, 0));
        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 102));
        jLabel24.setText("Contactno.");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(43, 285, 120, 22);
        jPanel3.add(txtcno1);
        txtcno1.setBounds(153, 283, 170, 30);

        jLabel25.setBackground(new java.awt.Color(102, 51, 0));
        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 102));
        jLabel25.setText("Department");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(400, 290, 130, 22);

        txtdept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdept1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtdept1);
        txtdept1.setBounds(540, 290, 170, 30);

        jLabel26.setBackground(new java.awt.Color(102, 51, 0));
        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 102));
        jLabel26.setText("Post");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(43, 323, 80, 22);

        txtpost1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpost1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtpost1);
        txtpost1.setBounds(153, 321, 170, 30);

        jLabel27.setBackground(new java.awt.Color(102, 51, 0));
        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 102));
        jLabel27.setText("Date of joining");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(400, 330, 150, 22);
        jPanel3.add(txtdoj1);
        txtdoj1.setBounds(540, 330, 170, 30);

        jLabel28.setBackground(new java.awt.Color(102, 51, 0));
        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 102));
        jLabel28.setText("Timing");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(43, 361, 100, 22);
        jPanel3.add(txttime1);
        txttime1.setBounds(153, 359, 170, 30);

        jLabel29.setBackground(new java.awt.Color(102, 51, 0));
        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 102));
        jLabel29.setText("Address");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(400, 370, 70, 22);
        jPanel3.add(txtaddress1);
        txtaddress1.setBounds(470, 370, 240, 30);

        jLabel30.setBackground(new java.awt.Color(102, 51, 0));
        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 102));
        jLabel30.setText("Hra");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(43, 399, 80, 22);

        txthra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthraKeyTyped(evt);
            }
        });
        jPanel3.add(txthra);
        txthra.setBounds(153, 397, 170, 30);

        jLabel31.setBackground(new java.awt.Color(102, 51, 0));
        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 102));
        jLabel31.setText("Total Salary");
        jPanel3.add(jLabel31);
        jLabel31.setBounds(210, 480, 130, 22);
        jPanel3.add(txttotal1);
        txttotal1.setBounds(350, 480, 160, 30);

        jLabel32.setBackground(new java.awt.Color(102, 51, 0));
        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 102));
        jLabel32.setText("Paid salary date");
        jPanel3.add(jLabel32);
        jLabel32.setBounds(404, 169, 150, 22);

        ok1.setBackground(new java.awt.Color(255, 255, 255));
        ok1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ok1.setText("OK");
        ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok1ActionPerformed(evt);
            }
        });
        jPanel3.add(ok1);
        ok1.setBounds(292, 128, 85, 23);

        jLabel33.setBackground(new java.awt.Color(102, 51, 0));
        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 102));
        jLabel33.setText("Da");
        jPanel3.add(jLabel33);
        jLabel33.setBounds(400, 400, 70, 22);

        txtda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdaKeyTyped(evt);
            }
        });
        jPanel3.add(txtda);
        txtda.setBounds(540, 410, 170, 30);

        jLabel34.setBackground(new java.awt.Color(102, 51, 0));
        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 102));
        jLabel34.setText("Ta");
        jPanel3.add(jLabel34);
        jLabel34.setBounds(43, 435, 70, 22);

        txtta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttaKeyTyped(evt);
            }
        });
        jPanel3.add(txtta);
        txtta.setBounds(153, 435, 170, 30);

        jLabel35.setBackground(new java.awt.Color(102, 51, 0));
        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 102));
        jLabel35.setText("Pf");
        jPanel3.add(jLabel35);
        jLabel35.setBounds(400, 440, 70, 22);

        txtpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpfKeyTyped(evt);
            }
        });
        jPanel3.add(txtpf);
        txtpf.setBounds(540, 450, 170, 30);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel2.add(exit);
        exit.setBounds(140, 20, 90, 30);

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete);
        delete.setBounds(20, 20, 100, 30);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(260, 520, 260, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpfKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_txtpfKeyTyped

    private void txttaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttaKeyTyped
        // TODO add your handling code here:
        int bs,ta;
        long ts;
        bs=Integer.parseInt(txtsalary1.getText());
        ta=Integer.parseInt(txtta.getText());
        ta=bs*ta/100;
        ts=ta+bs;
        txttotal1.setText(String.valueOf(ts));
}//GEN-LAST:event_txttaKeyTyped

    private void txtdaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdaKeyTyped
        // TODO add your handling code here:
        int bs,da;
        long ts;
        bs=Integer.parseInt(txtsalary1.getText());
        da=Integer.parseInt(txtda.getText());
        da=bs*da/100;
        ts=da+bs;
        txttotal1.setText(String.valueOf(ts));
}//GEN-LAST:event_txtdaKeyTyped

    private void ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok1ActionPerformed
        int sno;
        sno=Integer.parseInt(txtsno1.getText());
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:employee");
            Statement stmt=con.createStatement();
            String query;
            query="select * from salarytable where sno="+sno+"";
            ResultSet res=stmt.executeQuery(query);
            DateFormat df= new SimpleDateFormat("dd-MMM-yyyy");


            if(res.next()) {
                txteno1.setText(res.getString("eno"));
                txtsdate1.setText(df.format(res.getDate("sdate")));
                txtname1.setText((res.getString("name")));
                txtsalary1.setText((res.getString("salary")));
                txtdept1.setText((res.getString("dept")));
                txtpost1.setText((res.getString("post")));

                txttime1.setText((res.getString("timing")));
                txtage1.setText((res.getString("age")));
                txtcno1.setText((res.getString("contactno")));
                txtaddress1.setText((res.getString("address")));
                txtgender1.setText((res.getString("gender")));
                txtdoj1.setText(df.format(res.getDate("doj")));
                txthra.setText(res.getString("hra"));
                txtda.setText(res.getString("da"));
                txtta.setText(res.getString("ta"));
                txtpf.setText(res.getString("pf"));
                txttotal1.setText(res.getString("total"));
            } else
                JOptionPane.showMessageDialog(null, "Not found");

        } catch(Exception e) {
        }
}//GEN-LAST:event_ok1ActionPerformed

    private void txthraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthraKeyTyped
        // TODO add your handling code here:
        int bs,hra;
        long ts;
        bs=Integer.parseInt(txtsalary1.getText());
        hra=Integer.parseInt(txthra.getText());
        hra=bs*hra/100;
        ts=hra+bs;
        txttotal1.setText(String.valueOf(ts));
}//GEN-LAST:event_txthraKeyTyped

    private void txtpost1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpost1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtpost1ActionPerformed

    private void txtdept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdept1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtdept1ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.hide();
}//GEN-LAST:event_exitActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int eno,age;
        eno=Integer.parseInt(txtsno1.getText());
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:employee");
            Statement stmt=con.createStatement();
            int choice;
            choice =JOptionPane.showConfirmDialog(null, "Are u sure...??");
            if(choice==JOptionPane.YES_OPTION) {

                String query;
                query="delete from salarytable where sno="+eno+"";
                stmt.executeUpdate(query);
                txtsno1.setText("");
                txteno1.setText("");
                txtsdate1.setText("");
                txtname1.setText("");
                txtsalary1.setText("");
                txtaddress1.setText("");
                txtage1.setText("");
                txtgender1.setText("");
                txtcno1.setText("");
                txtdept1.setText("");
                txttime1.setText("");
                txtdoj1.setText("");
                txtpost1.setText("");
                txthra.setText("");
                txtda.setText("");
                txtta.setText("");
                txtpf.setText("");
                txttotal1.setText("");
                JOptionPane.showMessageDialog(null, "successfully deleted");
            }


        } catch(Exception e) {
        }
}//GEN-LAST:event_deleteActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deletepaidsalaryform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton ok1;
    private javax.swing.JTextField txtaddress1;
    private javax.swing.JTextField txtage1;
    private javax.swing.JTextField txtcno1;
    private javax.swing.JTextField txtda;
    private javax.swing.JTextField txtdept1;
    private javax.swing.JTextField txtdoj1;
    private javax.swing.JTextField txteno1;
    private javax.swing.JTextField txtgender1;
    private javax.swing.JTextField txthra;
    private javax.swing.JTextField txtname1;
    private javax.swing.JTextField txtpf;
    private javax.swing.JTextField txtpost1;
    private javax.swing.JTextField txtsalary1;
    private javax.swing.JTextField txtsdate1;
    private javax.swing.JTextField txtsno1;
    private javax.swing.JTextField txtta;
    private javax.swing.JTextField txttime1;
    private javax.swing.JTextField txttotal1;
    // End of variables declaration//GEN-END:variables

}
