/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package employeeproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Expert
 */
public class Leaveform extends javax.swing.JFrame {


    /**
     * Creates new form Leaveform
     */
    public Leaveform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtlid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtdatefrom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdateto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtreason = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        back = new javax.swing.JButton();
        combo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Leav ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 100, 70, 20);
        jPanel1.add(txtlid);
        txtlid.setBounds(210, 100, 240, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Select Employee ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 160, 140, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Employee name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 210, 140, 20);

        txtname.setEnabled(false);
        jPanel1.add(txtname);
        txtname.setBounds(210, 210, 240, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Date from");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 270, 100, 20);

        txtdatefrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatefromActionPerformed(evt);
            }
        });
        jPanel1.add(txtdatefrom);
        txtdatefrom.setBounds(210, 270, 240, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Date to");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 330, 70, 20);
        jPanel1.add(txtdateto);
        txtdateto.setBounds(210, 330, 240, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("Reason");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 380, 70, 20);
        jPanel1.add(txtreason);
        txtreason.setBounds(210, 380, 240, 30);

        save.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);
        save.setBounds(160, 440, 110, 30);

        back.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(280, 440, 110, 30);

        combo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EMPLOYEE ID" }));
        combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemStateChanged(evt);
            }
        });
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel1.add(combo);
        combo.setBounds(210, 150, 240, 30);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("LEAVE DETAILS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 30, 250, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdatefromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatefromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatefromActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       int lid=0;
      
       try
        {
            //combo.addItem("Employee ID");
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:employee");
             Statement stmt=con.createStatement();
            ResultSet res=stmt.executeQuery("select * from etable");
           
            while(res.next())
            {
                combo.addItem(res.getString("eno"));
            }
            
            txtlid.setEnabled(false);
           
           
      
             Statement stmt2=con.createStatement();
            ResultSet res2=stmt2.executeQuery("select * from leavetable");
            while(res2.next())
            {

                 lid=Integer.parseInt(res2.getString("lid"));
                                 
            }
            txtlid.setText(""+(lid+1));
        }
       catch(Exception e)
       {}
        
    }//GEN-LAST:event_formWindowActivated

    private void comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemStateChanged
        int eid;
        eid=Integer.parseInt(combo.getSelectedItem().toString());
        try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
             Connection con=DriverManager.getConnection("jdbc:odbc:employee");
             Statement stmt=con.createStatement();
            ResultSet res=stmt.executeQuery("select * from etable where eno="+eid);
            if(res.next())
            {

                 txtname.setText(res.getString("name"));
                 
            }
            
            txtname.setEnabled(false);
            txtdatefrom.requestFocus();
           
       }
       catch(Exception e)
       {}
        
    }//GEN-LAST:event_comboItemStateChanged

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
          int eid,lid;
          String dateto,datefrom,reason,name;
        try
        {
            eid=Integer.parseInt(combo.getSelectedItem().toString());
            lid=Integer.parseInt(txtlid.getText());
            datefrom=txtdatefrom.getText();
            dateto=txtdateto.getText();
            reason=txtreason.getText();
            name=txtname.getText();
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:employee");
            Statement stmt=con.createStatement();
            String query="insert into leavetable values("+lid+","+eid+",'"+name+"','"+datefrom+"','"+dateto+"','"+reason+"')";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Leave granted");
            txtname.setText("");
            txtdatefrom.setText("");
            txtdateto.setText("");
            txtreason.setText("");
            dispose();
            //combo.removeAllItems();
            
       }
       catch(Exception e)
       {}
    }//GEN-LAST:event_saveActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leaveform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leaveform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leaveform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leaveform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leaveform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton save;
    private javax.swing.JTextField txtdatefrom;
    private javax.swing.JTextField txtdateto;
    private javax.swing.JTextField txtlid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtreason;
    // End of variables declaration//GEN-END:variables
}
