/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * List_of_unpaid_salary.java
 *
 * Created on Jan 1, 2002, 12:17:00 AM
 */

package employeeproject;
import java.sql.*;
import javax.swing.table.*;


public class List_of_unpaid_salaryform extends javax.swing.JFrame {

    String mode="np";
    public List_of_unpaid_salaryform() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(649, 345, 93, 37);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("LIST OF UNPAID SALARY");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(459, 31, 451, 35);

        tb.setBackground(new java.awt.Color(204, 204, 255));
        tb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tb.setForeground(new java.awt.Color(0, 51, 102));
        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee Id", "Employee Name", "Fname", "Age", "Gender", "Contact No.", "Department", "Post", "Date Of Joining", "Timing", "Salary", "Email Id", "Address"
            }
        ));
        jScrollPane1.setViewportView(tb);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 89, 1320, 235);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1362, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     // String mode="np";
        DefaultTableModel m=(DefaultTableModel) tb.getModel();
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection c=DriverManager.getConnection("jdbc:odbc:employee");
            Statement state=c.createStatement();
            ResultSet res;
            String query;
            int row=m.getRowCount();
            for (int i=0;i<row;i++)
            {
                m.removeRow(0);
            }

                query="select * from etable where paymode='"+mode+"'";
                res=state.executeQuery(query);
                while(res.next()) {
                    m.addRow(new Object [] {res.getString("eno"),res.getString("name"),res.getString("fname"),res.getString("age"),res.getString("gender"),res.getString("contactno"),res.getString("dept"),res.getString("post"),res.getString("doj"),res.getString("timing"),res.getString("salary"),res.getString("emailid"),res.getString("address")} );
                }
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_formWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new List_of_unpaid_salaryform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables

}
