/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Mainwindow.java
 *
 * Created on Jun 11, 2014, 11:11:37 PM
 */

package employeeproject;
import java.awt.*;

/**
 *
 * @author Neeraj
 */
public class Mainwindow extends javax.swing.JFrame {

    /** Creates new form Mainwindow */
    public Mainwindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        addemp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        delemp = new javax.swing.JButton();
        searchemp = new javax.swing.JButton();
        modifyemp = new javax.swing.JButton();
        paysalary = new javax.swing.JButton();
        modifysalary = new javax.swing.JButton();
        searchsalary = new javax.swing.JButton();
        changepass = new javax.swing.JButton();
        report = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(11, 50, 105));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(100, 290, 100, 290, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("EMPLOYEE MANAGEMENT SYSTEM");

        panel.setBackground(new java.awt.Color(102, 0, 0));
        panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 10, true));
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelMouseMoved(evt);
            }
        });
        panel.setLayout(null);

        addemp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addemp.setForeground(new java.awt.Color(102, 0, 0));
        addemp.setText("ADD NEW EMPLOYEE");
        addemp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addempMouseMoved(evt);
            }
        });
        addemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addempActionPerformed(evt);
            }
        });
        panel.add(addemp);
        addemp.setBounds(88, 91, 241, 33);

        jLabel2.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("M A I N   M E N U");
        panel.add(jLabel2);
        jLabel2.setBounds(260, 30, 251, 40);

        delemp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        delemp.setForeground(new java.awt.Color(102, 0, 0));
        delemp.setText("DELETE EMPLOYEE");
        delemp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                delempMouseMoved(evt);
            }
        });
        delemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delempActionPerformed(evt);
            }
        });
        panel.add(delemp);
        delemp.setBounds(388, 91, 241, 33);

        searchemp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchemp.setForeground(new java.awt.Color(102, 0, 0));
        searchemp.setText("SEARCH EMPLOYEE ENTRY");
        searchemp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                searchempMouseMoved(evt);
            }
        });
        searchemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchempActionPerformed(evt);
            }
        });
        panel.add(searchemp);
        searchemp.setBounds(390, 130, 241, 33);

        modifyemp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        modifyemp.setForeground(new java.awt.Color(102, 0, 0));
        modifyemp.setText("MODIFY EMPLOYEE ENTRY");
        modifyemp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                modifyempMouseMoved(evt);
            }
        });
        modifyemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyempActionPerformed(evt);
            }
        });
        panel.add(modifyemp);
        modifyemp.setBounds(90, 130, 241, 33);

        paysalary.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        paysalary.setForeground(new java.awt.Color(102, 0, 0));
        paysalary.setText("PAY SALARY");
        paysalary.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                paysalaryMouseMoved(evt);
            }
        });
        paysalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paysalaryActionPerformed(evt);
            }
        });
        panel.add(paysalary);
        paysalary.setBounds(88, 175, 241, 33);

        modifysalary.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        modifysalary.setForeground(new java.awt.Color(102, 0, 0));
        modifysalary.setText("MODIFY PAID SALARY");
        modifysalary.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                modifysalaryMouseMoved(evt);
            }
        });
        modifysalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifysalaryActionPerformed(evt);
            }
        });
        panel.add(modifysalary);
        modifysalary.setBounds(88, 226, 241, 33);

        searchsalary.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchsalary.setForeground(new java.awt.Color(102, 0, 0));
        searchsalary.setText("SEARCH PAID SALARY ");
        searchsalary.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                searchsalaryMouseMoved(evt);
            }
        });
        searchsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchsalaryActionPerformed(evt);
            }
        });
        panel.add(searchsalary);
        searchsalary.setBounds(388, 175, 241, 33);

        changepass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        changepass.setForeground(new java.awt.Color(102, 0, 0));
        changepass.setText("CHANGE PASSWORD");
        changepass.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                changepassMouseMoved(evt);
            }
        });
        changepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepassActionPerformed(evt);
            }
        });
        panel.add(changepass);
        changepass.setBounds(388, 226, 241, 33);

        report.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        report.setForeground(new java.awt.Color(102, 0, 0));
        report.setText("RECORD");
        report.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                reportMouseMoved(evt);
            }
        });
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        panel.add(report);
        report.setBounds(88, 277, 241, 33);

        exit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(102, 0, 0));
        exit.setText("EXIT");
        exit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                exitMouseMoved(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        panel.add(exit);
        exit.setBounds(388, 277, 241, 33);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addempMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addempMouseMoved
        // TODO add your handling code here:
        addemp.setBackground(Color.blue);
    }//GEN-LAST:event_addempMouseMoved

    private void addempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addempActionPerformed
        Addemployeeform obj=new Addemployeeform();
        obj.show();
}//GEN-LAST:event_addempActionPerformed

    private void delempMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delempMouseMoved
        delemp.setBackground(Color.blue);
}//GEN-LAST:event_delempMouseMoved

    private void delempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delempActionPerformed
        Deleteemployeeform obj=new Deleteemployeeform();
        obj.show();
}//GEN-LAST:event_delempActionPerformed

    private void searchempMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchempMouseMoved
        searchemp.setBackground(Color.blue);
}//GEN-LAST:event_searchempMouseMoved

    private void searchempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchempActionPerformed
        SearchEmployeeform obj=new SearchEmployeeform();
        obj.show();
}//GEN-LAST:event_searchempActionPerformed

    private void modifyempMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyempMouseMoved
        modifyemp.setBackground(Color.blue);
}//GEN-LAST:event_modifyempMouseMoved

    private void modifyempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyempActionPerformed
        Modifyemployeeform obj=new Modifyemployeeform();
        obj.show();
}//GEN-LAST:event_modifyempActionPerformed

    private void paysalaryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paysalaryMouseMoved
        paysalary.setBackground(Color.blue);
}//GEN-LAST:event_paysalaryMouseMoved

    private void paysalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paysalaryActionPerformed
        Paysalaryform obj=new Paysalaryform();
        obj.show();
}//GEN-LAST:event_paysalaryActionPerformed

    private void modifysalaryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifysalaryMouseMoved
        modifysalary.setBackground(Color.blue);
}//GEN-LAST:event_modifysalaryMouseMoved

    private void modifysalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifysalaryActionPerformed
        modifypaidsalaryform obj=new modifypaidsalaryform();
        obj.show();
}//GEN-LAST:event_modifysalaryActionPerformed

    private void searchsalaryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchsalaryMouseMoved
        searchsalary.setBackground(Color.blue);
}//GEN-LAST:event_searchsalaryMouseMoved

    private void searchsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchsalaryActionPerformed
        Searchemployeepaidsalaryform obj=new Searchemployeepaidsalaryform();
        obj.show();
}//GEN-LAST:event_searchsalaryActionPerformed

    private void changepassMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepassMouseMoved
        changepass.setBackground(Color.blue);
}//GEN-LAST:event_changepassMouseMoved

    private void changepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepassActionPerformed
        ChangePasswordform obj=new ChangePasswordform();
        obj.show();
}//GEN-LAST:event_changepassActionPerformed

    private void reportMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseMoved
        report.setBackground(Color.blue);
}//GEN-LAST:event_reportMouseMoved

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        List_of_record_form obj=new List_of_record_form();
        obj.show();
}//GEN-LAST:event_reportActionPerformed

    private void exitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseMoved
        exit.setBackground(Color.blue);
}//GEN-LAST:event_exitMouseMoved

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
}//GEN-LAST:event_exitActionPerformed

    private void panelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseMoved
        addemp.setBackground(Color.cyan);
        report.setBackground(Color.cyan);
        delemp.setBackground(Color.cyan);
        modifyemp.setBackground(Color.cyan);
        searchemp.setBackground(Color.cyan);
        paysalary.setBackground(Color.cyan);
        
        modifysalary.setBackground(Color.cyan);
        searchsalary.setBackground(Color.cyan);
        changepass.setBackground(Color.cyan);
        exit.setBackground(Color.cyan);



    }//GEN-LAST:event_panelMouseMoved

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainwindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addemp;
    private javax.swing.JButton changepass;
    private javax.swing.JButton delemp;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modifyemp;
    private javax.swing.JButton modifysalary;
    private javax.swing.JPanel panel;
    private javax.swing.JButton paysalary;
    private javax.swing.JButton report;
    private javax.swing.JButton searchemp;
    private javax.swing.JButton searchsalary;
    // End of variables declaration//GEN-END:variables

}
