/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Modifyemployeeform.java
 *
 * Created on 2 Jun, 2014, 12:59:48 PM
 */

package employeeproject;
import javax.swing.*;
import java.sql.*;
import java.text.*;

/**
 *
 * @author hpworld
 */
public class Modifyemployeeform extends javax.swing.JFrame {

    /** Creates new form Modifyemployeeform */
    public Modifyemployeeform() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txteno = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtsalary = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtdept = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdoj = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txttime = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtpost = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtemailid = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        update = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("MODIFY  EMPLOYEE RECORD");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(187, 39, 460, 35);

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Employee ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(247, 90, 101, 22);

        jLabel3.setBackground(new java.awt.Color(255, 153, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(41, 194, 90, 22);

        txteno.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel1.add(txteno);
        txteno.setBounds(387, 89, 170, 30);

        txtname.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtname);
        txtname.setBounds(170, 190, 170, 30);

        jLabel5.setBackground(new java.awt.Color(255, 153, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Age");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(382, 194, 30, 22);

        txtage.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel1.add(txtage);
        txtage.setBounds(500, 190, 180, 30);

        ok.setBackground(new java.awt.Color(255, 255, 255));
        ok.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok);
        ok.setBounds(301, 137, 85, 23);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Salary");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 240, 90, 22);

        txtsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalaryActionPerformed(evt);
            }
        });
        jPanel1.add(txtsalary);
        txtsalary.setBounds(170, 240, 170, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Gender");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 250, 57, 22);
        jPanel1.add(txtgender);
        txtgender.setBounds(500, 240, 180, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Contact No.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 290, 120, 22);
        jPanel1.add(txtcno);
        txtcno.setBounds(170, 290, 170, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Department");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(380, 300, 92, 22);
        jPanel1.add(txtdept);
        txtdept.setBounds(500, 290, 180, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Date of joining");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 340, 130, 22);
        jPanel1.add(txtdoj);
        txtdoj.setBounds(170, 340, 170, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Timing");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(380, 350, 55, 22);
        jPanel1.add(txttime);
        txttime.setBounds(500, 340, 180, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Post");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 390, 80, 22);
        jPanel1.add(txtpost);
        txtpost.setBounds(170, 390, 170, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("Email ID");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(380, 400, 70, 22);
        jPanel1.add(txtemailid);
        txtemailid.setBounds(500, 390, 250, 30);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update);
        update.setBounds(30, 30, 110, 30);

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel2.add(exit);
        exit.setBounds(170, 30, 110, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(230, 510, 320, 90);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("Address");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(380, 440, 62, 22);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("Fname");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 440, 90, 22);
        jPanel1.add(txtfname);
        txtfname.setBounds(170, 440, 170, 30);

        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtaddress);
        txtaddress.setBounds(500, 440, 250, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtnameActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        int eno;
        eno=Integer.parseInt(txteno.getText());
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:employee");
            Statement stmt=con.createStatement();
            String query;
            query="select * from etable where eno="+eno+"";
            ResultSet res=stmt.executeQuery(query);
            DateFormat df= new SimpleDateFormat("dd-MMM-yyyy");


            if(res.next()) {
                txtname.setText((res.getString("name")));
                txtsalary.setText((res.getString("salary")));
                txtdept.setText((res.getString("dept")));
                txtpost.setText((res.getString("post")));

                txttime.setText((res.getString("timing")));
                txtage.setText((res.getString("age")));
                txtcno.setText((res.getString("contactno")));
                txtaddress.setText((res.getString("address")));
                txtgender.setText((res.getString("gender")));
                txtdoj.setText(df.format(res.getDate("doj")));
                txtfname.setText((res.getString("fname")));
                txtemailid.setText((res.getString("emailid")));
            } else
                JOptionPane.showMessageDialog(null, "Not found");

        } catch(Exception e) {
        }
}//GEN-LAST:event_okActionPerformed

    private void txtsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalaryActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtsalaryActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        int eno,age;
        long salary;
        String name,gender,dept,post,address,cno,time,doj,fname,eid;
        eno=Integer.parseInt(txteno.getText());
        age=Integer.parseInt(txtage.getText());
        salary=Long.parseLong(txtsalary.getText());
        name=txtname.getText();
        address=txtaddress.getText();
        gender=txtgender.getText();
        dept=txtdept.getText();
        post=txtpost.getText();
        cno=txtcno.getText();
        time=txttime.getText();
        doj=txtdoj.getText();
        fname=txtfname.getText();
        eid=txtemailid.getText();

        try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:employee");
            Statement stmt=con.createStatement();
            String query;
            query="update etable set name='"+name+"',salary="+salary+",age="+age+",gender='"+gender+"',contactno='"+cno+"',dept='"+dept+"',post='"+post+"',doj='"+doj+"',timing='"+time+"',address='"+address+"',fname='"+fname+"',emailid='"+eid+"'where eno="+eno+"";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "successfully update");
            txtname.setText("");
            txtsalary.setText("");
            txtemailid.setText("");
            txtage.setText("");
            txtgender.setText("");
            txtcno.setText("");
            txtdept.setText("");
            txttime.setText("");
            txtdoj.setText("");
            txtpost.setText("");
            txtfname.setText("");
            txtaddress.setText("");

       }
        catch(Exception e)
        {}
}//GEN-LAST:event_updateActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.hide();
}//GEN-LAST:event_exitActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtaddressActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modifyemployeeform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton ok;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcno;
    private javax.swing.JTextField txtdept;
    private javax.swing.JTextField txtdoj;
    private javax.swing.JTextField txtemailid;
    private javax.swing.JTextField txteno;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpost;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JTextField txttime;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

}
