/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * modifypaidsalaryform.java
 *
 * Created on 5 Jun, 2014, 12:24:50 PM
 */

package employeeproject;
import java.sql.*;
import javax.swing.*;
import java.awt.event.*;
import java.text.*;

/**
 *
 * @author hpworld
 */
public class modifypaidsalaryform extends javax.swing.JFrame {

    /** Creates new form modifypaidsalaryform */
    public modifypaidsalaryform() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtsno = new javax.swing.JTextField();
        txtsdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txteno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtsalary = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtdept = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtpost = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtdoj = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txttime = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txthra = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        update = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtda = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtta = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtpf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("MODIFY PAID SALARY RECORD");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 30, 480, 35);

        jLabel2.setBackground(new java.awt.Color(102, 51, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Enter paid salary no.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(199, 92, 180, 22);
        jPanel1.add(txtsno);
        txtsno.setBounds(410, 90, 170, 30);
        jPanel1.add(txtsdate);
        txtsdate.setBounds(577, 167, 180, 30);

        jLabel4.setBackground(new java.awt.Color(102, 51, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Employee no.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(43, 171, 140, 22);
        jPanel1.add(txteno);
        txteno.setBounds(173, 169, 180, 30);

        jLabel5.setBackground(new java.awt.Color(102, 51, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(43, 209, 90, 22);
        jPanel1.add(txtname);
        txtname.setBounds(173, 207, 180, 30);

        jLabel6.setBackground(new java.awt.Color(102, 51, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Salary");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(404, 203, 90, 22);
        jPanel1.add(txtsalary);
        txtsalary.setBounds(577, 201, 180, 30);

        jLabel7.setBackground(new java.awt.Color(102, 51, 0));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Age");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(43, 247, 70, 22);
        jPanel1.add(txtage);
        txtage.setBounds(173, 245, 180, 30);

        jLabel8.setBackground(new java.awt.Color(102, 51, 0));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(404, 243, 100, 22);
        jPanel1.add(txtgender);
        txtgender.setBounds(580, 240, 180, 30);

        jLabel9.setBackground(new java.awt.Color(102, 51, 0));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Contactno.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(43, 285, 120, 22);
        jPanel1.add(txtcno);
        txtcno.setBounds(173, 283, 180, 30);

        jLabel10.setBackground(new java.awt.Color(102, 51, 0));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Department");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(410, 280, 130, 22);

        txtdept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdeptActionPerformed(evt);
            }
        });
        jPanel1.add(txtdept);
        txtdept.setBounds(577, 277, 180, 30);

        jLabel11.setBackground(new java.awt.Color(102, 51, 0));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Post");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(43, 323, 80, 22);

        txtpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpostActionPerformed(evt);
            }
        });
        jPanel1.add(txtpost);
        txtpost.setBounds(173, 321, 180, 30);

        jLabel12.setBackground(new java.awt.Color(102, 51, 0));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("Date of joining");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(410, 320, 150, 22);
        jPanel1.add(txtdoj);
        txtdoj.setBounds(577, 315, 180, 30);

        jLabel13.setBackground(new java.awt.Color(102, 51, 0));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("Timing");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(43, 361, 100, 22);
        jPanel1.add(txttime);
        txttime.setBounds(173, 359, 180, 30);

        jLabel14.setBackground(new java.awt.Color(102, 51, 0));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("Address");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(410, 360, 100, 22);
        jPanel1.add(txtaddress);
        txtaddress.setBounds(497, 353, 260, 30);

        jLabel15.setBackground(new java.awt.Color(102, 51, 0));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("Hra");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(43, 399, 80, 22);

        txthra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthraKeyTyped(evt);
            }
        });
        jPanel1.add(txthra);
        txthra.setBounds(173, 397, 180, 30);

        jLabel16.setBackground(new java.awt.Color(102, 51, 0));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Total Salary");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(40, 480, 130, 22);
        jPanel1.add(txttotal);
        txttotal.setBounds(170, 480, 190, 30);

        jLabel17.setBackground(new java.awt.Color(102, 51, 0));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("Paid salary date");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(404, 169, 150, 22);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(102, 0, 0));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel2.add(exit);
        exit.setBounds(190, 10, 170, 50);

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(51, 0, 0));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update);
        update.setBounds(10, 10, 170, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(400, 470, 370, 70);

        ok.setBackground(new java.awt.Color(255, 255, 255));
        ok.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ok.setForeground(new java.awt.Color(153, 0, 0));
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok);
        ok.setBounds(320, 130, 90, 30);

        jLabel18.setBackground(new java.awt.Color(102, 51, 0));
        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("Da");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(410, 400, 70, 20);

        txtda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdaKeyTyped(evt);
            }
        });
        jPanel1.add(txtda);
        txtda.setBounds(580, 390, 180, 30);

        jLabel19.setBackground(new java.awt.Color(102, 51, 0));
        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 102));
        jLabel19.setText("Ta");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(43, 435, 70, 22);

        txtta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttaKeyTyped(evt);
            }
        });
        jPanel1.add(txtta);
        txtta.setBounds(173, 435, 180, 30);

        jLabel20.setBackground(new java.awt.Color(102, 51, 0));
        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setText("Pf");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(410, 440, 60, 22);

        txtpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpfKeyTyped(evt);
            }
        });
        jPanel1.add(txtpf);
        txtpf.setBounds(577, 432, 180, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdeptActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtdeptActionPerformed

    private void txtpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpostActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtpostActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
       this.hide();
}//GEN-LAST:event_exitActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        int sno;
        sno=Integer.parseInt(txtsno.getText());
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:employee");
            Statement stmt=con.createStatement();
            String query;
            query="select * from salarytable where sno="+sno+"";
            ResultSet res=stmt.executeQuery(query);
            DateFormat df= new SimpleDateFormat("dd-MMM-yyyy");


            if(res.next()) {
                txteno.setText(res.getString("eno"));
                txtsdate.setText(df.format(res.getDate("sdate")));
                txtname.setText((res.getString("name")));
                txtsalary.setText((res.getString("salary")));
                txtdept.setText((res.getString("dept")));
                txtpost.setText((res.getString("post")));

                txttime.setText((res.getString("timing")));
                txtage.setText((res.getString("age")));
                txtcno.setText((res.getString("contactno")));
                txtaddress.setText((res.getString("address")));
                txtgender.setText((res.getString("gender")));
                txtdoj.setText(df.format(res.getDate("doj")));
                txthra.setText(res.getString("hra"));
                txtda.setText(res.getString("da"));
                txtta.setText(res.getString("ta"));
                txtpf.setText(res.getString("pf"));
                txttotal.setText(res.getString("total"));
            } else
                JOptionPane.showMessageDialog(null, "Not found");

        } catch(Exception e) {
        }
}//GEN-LAST:event_okActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        int eno,age,hra,ta,da,pf,sno;
        long salary;
        String name,gender,dept,post,address,cno,time,doj,dos,ts;
        sno=Integer.parseInt(txtsno.getText());
        eno=Integer.parseInt(txteno.getText());
        dos=txtsdate.getText();
        eno=Integer.parseInt(txteno.getText());
        age=Integer.parseInt(txtage.getText());
        salary=Long.parseLong(txtsalary.getText());
        name=txtname.getText();
        address=txtaddress.getText();
        gender=txtgender.getText();
        dept=txtdept.getText();
        post=txtpost.getText();
        cno=txtcno.getText();
        time=txttime.getText();
        doj=txtdoj.getText();
        hra=Integer.parseInt(txthra.getText());
        da=Integer.parseInt(txtda.getText());
        ta=Integer.parseInt(txtta.getText());
        pf=Integer.parseInt(txtpf.getText());
        ts=txttotal.getText();
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:employee");
            Statement stmt=con.createStatement();
            String query;
            query="update salarytable set sdate='"+dos+"',eno="+eno+",name='"+name+"',salary="+salary+",age="+age+",gender='"+gender+"',contactno='"+cno+"',dept='"+dept+"',post='"+post+"',doj='"+doj+"',timing='"+time+"',address='"+address+"',hra="+hra+",da="+da+",ta="+ta+",pf="+pf+",total='"+ts+"'where sno="+sno+"";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "successfully update");
            txtsno.setText("");
            txteno.setText("");
            txtsdate.setText("");
            txtname.setText("");
            txtsalary.setText("");
            txtaddress.setText("");
            txtage.setText("");
            txtgender.setText("");
            txtcno.setText("");
            txtdept.setText("");
            txttime.setText("");
            txtdoj.setText("");
            txtpost.setText("");
            txthra.setText("");
            txtda.setText("");
            txtta.setText("");
            txtpf.setText("");
            txttotal.setText("");



        } catch(Exception e) {
        }
}//GEN-LAST:event_updateActionPerformed

    private void txthraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthraKeyTyped
        // TODO add your handling code here:
         int bs,hra;
         long ts;
         bs=Integer.parseInt(txtsalary.getText());
         hra=Integer.parseInt(txthra.getText());
         hra=bs*hra/100;
         ts=hra+bs;
         txttotal.setText(String.valueOf(ts));
}//GEN-LAST:event_txthraKeyTyped

    private void txtdaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdaKeyTyped
        // TODO add your handling code here:
          int bs,da;
         long ts;
         bs=Integer.parseInt(txtsalary.getText());
         da=Integer.parseInt(txtda.getText());
         da=bs*da/100;
         ts=da+bs;
         txttotal.setText(String.valueOf(ts));
}//GEN-LAST:event_txtdaKeyTyped

    private void txttaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttaKeyTyped
        // TODO add your handling code here:
          int bs,ta;
         long ts;
         bs=Integer.parseInt(txtsalary.getText());
         ta=Integer.parseInt(txtta.getText());
         ta=bs*ta/100;
         ts=ta+bs;
         txttotal.setText(String.valueOf(ts));
}//GEN-LAST:event_txttaKeyTyped

    private void txtpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpfKeyTyped
        // TODO add your handling code here:
      
}//GEN-LAST:event_txtpfKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modifypaidsalaryform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton ok;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcno;
    private javax.swing.JTextField txtda;
    private javax.swing.JTextField txtdept;
    private javax.swing.JTextField txtdoj;
    private javax.swing.JTextField txteno;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txthra;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpf;
    private javax.swing.JTextField txtpost;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JTextField txtsdate;
    private javax.swing.JTextField txtsno;
    private javax.swing.JTextField txtta;
    private javax.swing.JTextField txttime;
    private javax.swing.JTextField txttotal;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

}
