/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchEmployeeform.java
 *
 * Created on 2 Jun, 2014, 1:26:26 PM
 */

package employeeproject;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.*;

/**
 *
 * @author hpworld
 */
public class SearchEmployeeform extends javax.swing.JFrame {

    /** Creates new form SearchEmployeeform */
    public SearchEmployeeform() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        op1 = new javax.swing.JRadioButton();
        op2 = new javax.swing.JRadioButton();
        lbl = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(155, 153, 0));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("SEARCH EMPLOYEE FORM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 40, 410, 35);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("S E A R C H  O P T I O N");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(509, 96, 205, 22);

        op1.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(op1);
        op1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        op1.setForeground(new java.awt.Color(0, 0, 102));
        op1.setText("Enter Employee Id");
        op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1ActionPerformed(evt);
            }
        });
        jPanel1.add(op1);
        op1.setBounds(535, 128, 153, 25);

        op2.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(op2);
        op2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        op2.setForeground(new java.awt.Color(0, 0, 102));
        op2.setText("Enter Employee Name");
        op2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op2ActionPerformed(evt);
            }
        });
        jPanel1.add(op2);
        op2.setBounds(535, 153, 179, 25);

        lbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl.setForeground(new java.awt.Color(102, 0, 102));
        lbl.setText("Enter Employee No:-");
        jPanel1.add(lbl);
        lbl.setBounds(420, 190, 170, 22);
        jPanel1.add(t1);
        t1.setBounds(600, 190, 160, 30);

        tb.setBackground(new java.awt.Color(204, 204, 255));
        tb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tb.setForeground(new java.awt.Color(153, 0, 0));
        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee Id", "Employee Name", "Salary", "Age", "Gender", "Contact No.", "Department", "Post", "Date Of Joining", "Timing", "Address"
            }
        ));
        jScrollPane1.setViewportView(tb);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 283, 1173, 235);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(506, 240, 89, 25);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(623, 240, 91, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1225, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1ActionPerformed
        // TODO add your handling code here:
        lbl.setText("Enter Employee Id");
        t1.requestFocus();
    }//GEN-LAST:event_op1ActionPerformed

    private void op2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op2ActionPerformed
        // TODO add your handling code here:
        lbl.setText("Enter Employee Name");
        t1.requestFocus();
    }//GEN-LAST:event_op2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel m=(DefaultTableModel) tb.getModel();
        try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection c=DriverManager.getConnection("jdbc:odbc:employee");
            Statement state=c.createStatement();
            ResultSet res;
            String query;
            int row=m.getRowCount();
           for (int i=0;i<row;i++)
           {
               m.removeRow(0);
           }
           if(op1.isSelected())
           {
               int s=Integer.parseInt(t1.getText());
               query="select * from etable where eno="+s;
               res=state.executeQuery(query);
               while(res.next())
               {
                   m.addRow(new Object [] {res.getString("eno"),res.getString("name"),res.getString("salary"),res.getString("age"),res.getString("gender"),res.getString("contactno"),res.getString("dept"),res.getString("post"),res.getString("doj"),res.getString("timing"),res.getString("address")} );
               }
           }
           else if(op2.isSelected())
           {
               String s=t1.getText();
               query="select * from etable where name='"+s+"'";
               res=state.executeQuery(query);
               while(res.next())
               {
                    m.addRow(new Object [] {res.getString("eno"),res.getString("name"),res.getString("salary"),res.getString("age"),res.getString("gender"),res.getString("contactno"),res.getString("dept"),res.getString("post"),res.getString("doj"),res.getString("timing"),res.getString("address")} );
               }
           }
        }
        catch (Exception e)
        {}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchEmployeeform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op2;
    private javax.swing.JTextField t1;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables

}
