/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package employeeproject;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.*;


/**
 *
 * @author Expert
 */
public class Searchdepartment extends javax.swing.JFrame {

    /**
     * Creates new form Searchdepartment
     */
    public Searchdepartment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ob1 = new javax.swing.JRadioButton();
        ob2 = new javax.swing.JRadioButton();
        lbl = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("SEARCH DEPARTMENT DETAILS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 10, 470, 35);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("OPTIONS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 70, 130, 28);

        ob1.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(ob1);
        ob1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ob1.setForeground(new java.awt.Color(0, 0, 102));
        ob1.setText("search by department no");
        ob1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ob1ActionPerformed(evt);
            }
        });
        jPanel1.add(ob1);
        ob1.setBounds(240, 110, 201, 25);

        ob2.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(ob2);
        ob2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ob2.setForeground(new java.awt.Color(0, 0, 102));
        ob2.setText("search by departmrnt name");
        ob2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ob2ActionPerformed(evt);
            }
        });
        jPanel1.add(ob2);
        ob2.setBounds(240, 130, 217, 25);

        lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl.setForeground(new java.awt.Color(153, 0, 0));
        lbl.setText("Enter the dept no");
        jPanel1.add(lbl);
        lbl.setBounds(190, 180, 129, 17);
        jPanel1.add(txt);
        txt.setBounds(320, 180, 149, 20);

        search.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(230, 220, 80, 30);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DNO", "DNAME", "POST"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 270, 537, 188);

        exit.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(320, 220, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ob1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ob1ActionPerformed
        lbl.setText("Ente the dept no");
        txt.requestFocus();
    }//GEN-LAST:event_ob1ActionPerformed

    private void ob2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ob2ActionPerformed
        lbl.setText("Enter the dept name");
        txt.requestFocus();
    }//GEN-LAST:event_ob2ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con=DriverManager.getConnection("jdbc:odbc:employee");
            Statement state=con.createStatement();
            String q=null;
            if(ob1.isSelected())
            {
                q="select  *  from   depttable where did="+txt.getText();
            }
            else if(ob2.isSelected())
            {
                q="select  *  from  depttable where dname='"+txt.getText()+"'";
            }
            
            ResultSet res=state.executeQuery(q);
            DefaultTableModel m=(DefaultTableModel)tbl.getModel();
            //removing all rows
            int n=m.getRowCount();
            for(int i=0;i<n;i++)
            m.removeRow(0);
            while(res.next())
            {
                Object newrow[]={res.getString(1),res.getString(2),res.getString(3)};
                m.addRow(newrow);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_searchActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Searchdepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Searchdepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Searchdepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Searchdepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Searchdepartment().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl;
    private javax.swing.JRadioButton ob1;
    private javax.swing.JRadioButton ob2;
    private javax.swing.JButton search;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}
